import "./globals.css";
import { Varela_Round } from "next/font/google";

const varela = Varela_Round({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Xpenses",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={varela.className} style={{ background: "#000000" }}>
        {children}
      </body>
    </html>
  );
}
